language: dart
sudo: false

os:
  - linux

dart:
  - dev
  - stable

script: ./tools/travis.sh

dart_task:
  - test: -p vm
  - dartfmt
  - dartanalyzer: --strong --fatal-warnings --fatal-lints lib/ test/