language: dart
sudo: false

os:
  - linux

dart:
  - dev
  - stable

script: 
  - ./tools/travis.sh
  - pub run test -p vm
  - dartfmt
  - dartanalyzer --strong --fatal-warnings --fatal-lints lib/ test/
