language: dart
sudo: false

os:
  - linux

dart:
  - dev

script:
  - ./tools/travis.sh
  - dart --preview-dart-2 test/test_all.dart
  - dartfmt -n --set-exit-if-changed .
  - dartanalyzer --strong --fatal-warnings --fatal-lints lib/ test/
