linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_init_to_null
    - await_only_futures
    - camel_case_types
    - cancel_subscriptions
    - constant_identifier_names
    - control_flow_in_finally
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - iterable_contains_unrelated_type
    - library_names
    - library_prefixes
    - list_remove_unrelated_type
    - non_constant_identifier_names
    - only_throw_errors
    - overridden_fields
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_not_empty
    - slash_for_doc_comments
    - sort_unnamed_constructors_first
    - super_goes_last
    - test_types_in_equals
    - type_init_formals
    - throw_in_finally
    - unnecessary_getters_setters
    - unrelated_type_equality_checks
    - valid_regexps
